server:
  servlet:
    context-path: /springai
spring:
  ai:
    openai:
      api-key: ${OPENAI_KEY}
      chat:
        options:
          model: gpt-4o #gpt-4-turbo, gpt-4o, gpt-3.5-turbo
          temperature: 0.7
          max-completion-tokens: 180
logging:
  level:
    org:
      springframework:
        ai.chat.client.advisor.SimpleLoggerAdvisor: DEBUG

weather:
  api-key :
  api-url : http://api.weatherapi.com/v1

currency-exchange:
  api-key :
  base-url: https://openexchangerates.org/api